$(document).ready(function(){
	var data = { items: [
	{value: "Afghanistan", country: "Afghanistan"},
	{value: "Albania ", country: "Albania "},
	{value: "Algeria", country: "Algeria"},
	{value: "Angola", country: "Angola"},
	{value: "Argentina", country: "Argentina"},
	{value: "Armenia ", country: "Armenia "},
	{value: "Aruba", country: "Aruba"},
	{value: "Australia ", country: "Australia "},
	{value: "Austria", country: "Austria"},
	{value: "Azerbaijan ", country: "Azerbaijan "},
	{value: "Bahamas", country: "Bahamas"},
	{value: "Bahrain", country: "Bahrain"},
	{value: "Bangladesh", country: "Bangladesh"},
	{value: "Barbados", country: "Barbados"},
	{value: "Belarus", country: "Belarus"},
	{value: "Belgium", country: "Belgium"},
	{value: "Belize", country: "Belize"},
	{value: "Benin", country: "Benin"},
	{value: "Bhutan", country: "Bhutan"},
	{value: "Bolivia (Plurinational State of)", country: "Bolivia (Plurinational State of)"},
	{value: "Bosnia and Herzegovina ", country: "Bosnia and Herzegovina "},
	{value: "Botswana", country: "Botswana"},
	{value: "Brazil", country: "Brazil"},
	{value: "Brunei Darussalam", country: "Brunei Darussalam"},
	{value: "Bulgaria", country: "Bulgaria"},
	{value: "Burkina Faso", country: "Burkina Faso"},
	{value: "Burundi", country: "Burundi"},
	{value: "Cambodia", country: "Cambodia"},
	{value: "Cameroon", country: "Cameroon"},
	{value: "Canada ", country: "Canada "},
	{value: "Cape Verde", country: "Cape Verde"},
	{value: "Central African Republic", country: "Central African Republic"},
	{value: "Chad", country: "Chad"},
	{value: "Channel Islands ", country: "Channel Islands "},
	{value: "Chile", country: "Chile"},
	{value: "China", country: "China"},
	{value: "China, Hong Kong Special Administrative Region", country: "China, Hong Kong Special Administrative Region"},
	{value: "China, Macao Special Administrative Region", country: "China, Macao Special Administrative Region"},
	{value: "Colombia", country: "Colombia"},
	{value: "Comoros", country: "Comoros"},
	{value: "Congo", country: "Congo"},
	{value: "Costa Rica", country: "Costa Rica"},
	{value: "Côte d'Ivoire", country: "Côte d'Ivoire"},
	{value: "Croatia ", country: "Croatia "},
	{value: "Cuba", country: "Cuba"},
	{value: "Cyprus", country: "Cyprus"},
	{value: "Czech Republic", country: "Czech Republic"},
	{value: "Democratic People's Republic of Korea", country: "Democratic People's Republic of Korea"},
	{value: "Democratic Republic of the Congo", country: "Democratic Republic of the Congo"},
	{value: "Denmark ", country: "Denmark "},
	{value: "Djibouti", country: "Djibouti"},
	{value: "Dominican Republic", country: "Dominican Republic"},
	{value: "Eastern Africa", country: "Eastern Africa"},
	{value: "Ecuador", country: "Ecuador"},
	{value: "Egypt", country: "Egypt"},
	{value: "El Salvador", country: "El Salvador"},
	{value: "Equatorial Guinea", country: "Equatorial Guinea"},
	{value: "Eritrea", country: "Eritrea"},
	{value: "Estonia ", country: "Estonia "},
	{value: "Ethiopia", country: "Ethiopia"},
	{value: "Fiji", country: "Fiji"},
	{value: "Finland ", country: "Finland "},
	{value: "France", country: "France"},
	{value: "French Guiana", country: "French Guiana"},
	{value: "French Polynesia", country: "French Polynesia"},
	{value: "Gabon", country: "Gabon"},
	{value: "Gambia", country: "Gambia"},
	{value: "Georgia ", country: "Georgia "},
	{value: "Germany", country: "Germany"},
	{value: "Ghana", country: "Ghana"},
	{value: "Greece ", country: "Greece "},
	{value: "Grenada", country: "Grenada"},
	{value: "Guadeloupe", country: "Guadeloupe"},
	{value: "Guam", country: "Guam"},
	{value: "Guatemala", country: "Guatemala"},
	{value: "Guinea", country: "Guinea"},
	{value: "Guinea-Bissau", country: "Guinea-Bissau"},
	{value: "Guyana", country: "Guyana"},
	{value: "Haiti", country: "Haiti"},
	{value: "Honduras", country: "Honduras"},
	{value: "Hungary", country: "Hungary"},
	{value: "Iceland ", country: "Iceland "},
	{value: "India", country: "India"},
	{value: "Indonesia", country: "Indonesia"},
	{value: "Iran (Islamic Republic of)", country: "Iran (Islamic Republic of)"},
	{value: "Iraq", country: "Iraq"},
	{value: "Ireland ", country: "Ireland "},
	{value: "Israel", country: "Israel"},
	{value: "Italy ", country: "Italy "},
	{value: "Jamaica", country: "Jamaica"},
	{value: "Japan ", country: "Japan "},
	{value: "Jordan", country: "Jordan"},
	{value: "Kazakhstan ", country: "Kazakhstan "},
	{value: "Kenya", country: "Kenya"},
	{value: "Kuwait", country: "Kuwait"},
	{value: "Kyrgyzstan ", country: "Kyrgyzstan "},
	{value: "Lao People's Democratic Republic", country: "Lao People's Democratic Republic"},
	{value: "Latvia ", country: "Latvia "},
	{value: "Lebanon", country: "Lebanon"},
	{value: "Lesotho", country: "Lesotho"},
	{value: "Liberia", country: "Liberia"},
	{value: "Libyan Arab Jamahiriya", country: "Libyan Arab Jamahiriya"},
	{value: "Lithuania ", country: "Lithuania "},
	{value: "Luxembourg", country: "Luxembourg"},
	{value: "Madagascar", country: "Madagascar"},
	{value: "Malawi", country: "Malawi"},
	{value: "Malaysia", country: "Malaysia"},
	{value: "Maldives", country: "Maldives"},
	{value: "Mali", country: "Mali"},
	{value: "Malta ", country: "Malta "},
	{value: "Martinique", country: "Martinique"},
	{value: "Mauritania", country: "Mauritania"},
	{value: "Mauritius", country: "Mauritius"},
	{value: "Mayotte", country: "Mayotte"},
	{value: "Mexico", country: "Mexico"},
	{value: "Micronesia (Federated States of)", country: "Micronesia (Federated States of)"},
	{value: "Mongolia", country: "Mongolia"},
	{value: "Montenegro ", country: "Montenegro "},
	{value: "Morocco", country: "Morocco"},
	{value: "Mozambique", country: "Mozambique"},
	{value: "Myanmar", country: "Myanmar"},
	{value: "Namibia", country: "Namibia"},
	{value: "Nepal", country: "Nepal"},
	{value: "Netherlands", country: "Netherlands"},
	{value: "Netherlands Antilles", country: "Netherlands Antilles"},
	{value: "New Caledonia", country: "New Caledonia"},
	{value: "New Zealand ", country: "New Zealand "},
	{value: "Nicaragua", country: "Nicaragua"},
	{value: "Niger", country: "Niger"},
	{value: "Nigeria", country: "Nigeria"},
	{value: "Norway ", country: "Norway "},
	{value: "Occupied Palestinian Territory", country: "Occupied Palestinian Territory"},
	{value: "Oman", country: "Oman"},
	{value: "Pakistan", country: "Pakistan"},
	{value: "Panama", country: "Panama"},
	{value: "Papua New Guinea", country: "Papua New Guinea"},
	{value: "Paraguay", country: "Paraguay"},
	{value: "Peru", country: "Peru"},
	{value: "Philippines", country: "Philippines"},
	{value: "Poland", country: "Poland"},
	{value: "Portugal ", country: "Portugal "},
	{value: "Puerto Rico", country: "Puerto Rico"},
	{value: "Qatar", country: "Qatar"},
	{value: "Republic of Korea", country: "Republic of Korea"},
	{value: "Republic of Moldova", country: "Republic of Moldova"},
	{value: "Réunion", country: "Réunion"},
	{value: "Romania", country: "Romania"},
	{value: "Russian Federation", country: "Russian Federation"},
	{value: "Rwanda", country: "Rwanda"},
	{value: "Saint Lucia", country: "Saint Lucia"},
	{value: "Saint Vincent and the Grenadines", country: "Saint Vincent and the Grenadines"},
	{value: "Samoa", country: "Samoa"},
	{value: "Sao Tome and Principe", country: "Sao Tome and Principe"},
	{value: "Saudi Arabia", country: "Saudi Arabia"},
	{value: "Senegal", country: "Senegal"},
	{value: "Serbia ", country: "Serbia "},
	{value: "Sierra Leone", country: "Sierra Leone"},
	{value: "Singapore", country: "Singapore"},
	{value: "Slovakia", country: "Slovakia"},
	{value: "Slovenia ", country: "Slovenia "},
	{value: "Solomon Islands", country: "Solomon Islands"},
	{value: "Somalia", country: "Somalia"},
	{value: "South Africa", country: "South Africa"},
	{value: "Spain ", country: "Spain "},
	{value: "Sri Lanka", country: "Sri Lanka"},
	{value: "Sudan ", country: "Sudan "},
	{value: "Suriname", country: "Suriname"},
	{value: "Swaziland", country: "Swaziland"},
	{value: "Sweden ", country: "Sweden "},
	{value: "Switzerland", country: "Switzerland"},
	{value: "Syrian Arab Republic", country: "Syrian Arab Republic"},
	{value: "Tajikistan ", country: "Tajikistan "},
	{value: "Thailand", country: "Thailand"},
	{value: "The former Yugoslav Republic of Macedonia ", country: "The former Yugoslav Republic of Macedonia "},
	{value: "Timor-Leste", country: "Timor-Leste"},
	{value: "Togo", country: "Togo"},
	{value: "Tonga", country: "Tonga"},
	{value: "Trinidad and Tobago", country: "Trinidad and Tobago"},
	{value: "Tunisia", country: "Tunisia"},
	{value: "Turkey", country: "Turkey"},
	{value: "Turkmenistan ", country: "Turkmenistan "},
	{value: "Uganda", country: "Uganda"},
	{value: "Ukraine", country: "Ukraine"},
	{value: "United Arab Emirates", country: "United Arab Emirates"},
	{value: "United Kingdom of Great Britain and Northern Ireland ", country: "United Kingdom of Great Britain and Northern Ireland "},
	{value: "United Republic of Tanzania", country: "United Republic of Tanzania"},
	{value: "United States of America ", country: "United States of America "},
	{value: "United States Virgin Islands", country: "United States Virgin Islands"},
	{value: "Uruguay", country: "Uruguay"},
	{value: "Uzbekistan ", country: "Uzbekistan "},
	{value: "Vanuatu", country: "Vanuatu"},
	{value: "Venezuela (Bolivarian Republic of)", country: "Venezuela (Bolivarian Republic of)"},
	{value: "Viet Nam", country: "Viet Nam"},
	{value: "Western Sahara", country: "Western Sahara"},
	{value: "Yemen", country: "Yemen"},
	{value: "Zambia", country: "Zambia"},
	{value: "Jawaharlal Nehru", country: "Jawaharlal Nehru"},
	{value: "Vallabhbhai Patel", country: "Vallabhbhai Patel"},
	{value: "Mohandas K. Gandhi", country: "Mohandas K. Gandhi"},
	{value: "Rajendra Prasad", country: "Rajendra Prasad"},
	{value: "Babu Jagjivan Ram", country: "Babu Jagjivan Ram"},
	{value: "C. Rajagopalachari", country: "C. Rajagopalachari"},
	{value: "Abul Kalam Azad", country: "Abul Kalam Azad"},
	{value: "J.B. Kriplani", country: "J.B. Kriplani"},
	{value: "Sarojini Naidu", country: "Sarojini Naidu"},
	{value: "Pattabhi Sitaraimayya", country: "Pattabhi Sitaraimayya"},
	{value: "Muhammad Ali Jinnah", country: "Muhammad Ali Jinnah"},
	{value: "Liaquat Ali Khan", country: "Liaquat Ali Khan"},
	{value: "Chaudhry Khaliquzzaman", country: "Chaudhry Khaliquzzaman"},
	{value: "Choudhary Rahmat Ali", country: "Choudhary Rahmat Ali"},
	{value: "Sikandar Hayat Khan", country: "Sikandar Hayat Khan"},
	{value: "Maulana Zafar Ali Khan", country: "Maulana Zafar Ali Khan"},
	{value: "A.K. Fazlul Huq", country: "A.K. Fazlul Huq"},
	{value: "Major General Lashmer Whistler", country: "Major General Lashmer Whistler"},
	{value: "Maj. Gen. Frederick Joseph Loftus-Tottenham", country: "Maj. Gen. Frederick Joseph Loftus-Tottenham"},
	{value: "Junagadh", country: "Junagadh"},
	{value: "Bantva", country: "Bantva"},
	{value: "Manavadar", country: "Manavadar"},
	{value: "Sardargarh", country: "Sardargarh"},
	{value: "Hyderabad", country: "Hyderabad"},
	{value: "Kashmir and Jammu", country: "Kashmir and Jammu"},
	{value: "Baroda", country: "Baroda"},
	{value: "Bikaner", country: "Bikaner"},
	{value: "Gwalior", country: "Gwalior"},
	{value: "Patiala", country: "Patiala"},
	{value: "Rewa", country: "Rewa"},
	{value: "Zimbabwe", country: "Zimbabwe"}
	
	]};
	$("#1st_c_pref").autoSuggest(data.items, {asHtmlID:"1st_c_pref",selectedItemProp: "country", searchObjProps: "country",selectionLimit:5,startText:"Enter countries"});
	$("#2nd_c_pref").autoSuggest(data.items, {asHtmlID:"2nd_c_pref",selectedItemProp: "country", searchObjProps: "country",selectionLimit:5,startText:"Enter countries"});
	$("#3rd_c_pref").autoSuggest(data.items, {asHtmlID:"3rd_c_pref",selectedItemProp: "country", searchObjProps: "country",selectionLimit:5,startText:"Enter countries"});
	$("#4th_c_pref").autoSuggest(data.items, {asHtmlID:"4th_c_pref",selectedItemProp: "country", searchObjProps: "country",selectionLimit:5,startText:"Enter countries"});
	$("#5th_c_pref").autoSuggest(data.items, {asHtmlID:"5th_c_pref",selectedItemProp: "country", searchObjProps: "country",selectionLimit:5,startText:"Enter countries"});
	$("#6th_c_pref").autoSuggest(data.items, {asHtmlID:"6th_c_pref",selectedItemProp: "country", searchObjProps: "country",selectionLimit:5,startText:"Enter countries"});
	$('form').ketchup();
	
});